### PR TITLE
Playwright: Install dependencies

### LINKED ISSUE #4: Setup Microsoft Playwright
## TODO

- [ ] Install Playwright and related dependencies

### PR DESCRIPTION
**Pull request by hariclerry**
### Tickets
Closes #4 

### What does this PR do?
This PR installs Microsoft Playwright

### What are the changes made?
- Installed Microsoft Playwright

### Screen shots
None

### CODE REVIEW

**Comment by sovoid** [comment]
@hariclerry please add an additional heading called Tickets and mention the issue this PR closes:

```
Closes #<issue-number>
```

**Review by sovoid — CHANGES_REQUESTED** [review]
Please change the PR title to:

```Playwright: Install dependencies```

**Comment by hariclerry** [comment]
> Please change the PR title to:
> 
> `Playwright: Install dependencies`

This has been changed @und3fined-v01d.

**Comment by sovoid** [comment]
@hariclerry same here. Please make pulls from upstream either in a separate PR or directly on the master

**Pull request closed without merging**
